### ISSUE TITLE
请问寒蝉手拙体是否可以修改并添加字符？

### ISSUE THREAD

**Issue by UltimateLin** [Warren2060/Chill-Zhuo#1]
你好：

我们发现贵字体中缺少中文冒号”：“（Unicode：U+FF1A）。请问是否可以在FontForge中添加此字符，并且用于商用游戏中，感谢。

**Comment by Warren2060** [comment]
可以的&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月18日(星期四) 下午4:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [Warren2060/Chill-Zhuo] 请问寒蝉手拙体是否可以修改并添加字符？ (Issue #1)





 
你好：
 
我们发现贵字体中缺少中文冒号”：“（Unicode：U+FF1A）。请问是否可以在FontForge中添加此字符，并且用于商用游戏中，感谢。

**Comment by UltimateLin** [comment]
谢谢
